osalas3Proj7:  Osalas3Proj7.cpp GridDisplay.o Creature.o Land.o Ant.o Doodlebug.o
	g++ -g -o osalas3Proj7 Osalas3Proj7.cpp GridDisplay.o Creature.o Land.o Ant.o Doodlebug.o

GridDisplay.o: GridDisplay.cpp GridDisplay.h
	g++ -c GridDisplay.cpp

Creature.o: Creature.cpp Creature.h
	g++ -c Creature.cpp

Land.o: Land.cpp Land.h
	g++ -c Land.cpp

Ant.o: Ant.cpp Ant.h
	g++ -c Ant.cpp

Doodlebug.o: Doodlebug.cpp Doodlebug.h
	g++ -c Doodlebug.cpp

clean:
	rm -f *.o Proj7